// Code generated by "gogen option -n service -r repo,newAggregate --with-init --lowercase"; DO NOT EDIT.

package dgo

import "fmt"

// newService constructor
func newService[A AggBase](repo Repo[A], newAggregate func() A, _opts ...ServiceOption[A]) *service[A] {
	_s := new(service[A])

	_s.repo = repo
	_s.newAggregate = newAggregate

	_s.SetOptions(_opts...)

	_s.init()
	return _s
}

// ServiceOption[A AggBase] option interface
type ServiceOption[A AggBase] interface {
	apply(*service[A])
}

// ServiceOption[A AggBase] option function
type serviceOptionFunc[A AggBase] func(*service[A])

func (f serviceOptionFunc[A]) apply(_s *service[A]) {
	f(_s)
}

func (_s *service[A]) SetOptions(_opts ...ServiceOption[A]) *service[A] {
	for _, _opt := range _opts {
		_opt.apply(_s)
	}
	return _s
}

func SkipServiceOption[A AggBase]() ServiceOption[A] {
	return serviceOptionFunc[A](func(_s *service[A]) {
		return
	})
}

func WithServiceOptions[A AggBase](o *serviceOptions[A]) ServiceOption[A] {
	return serviceOptionFunc[A](func(_s *service[A]) {
		_s.SetOptions(o.opts...)
	})
}

// serviceOptions[A AggBase] options struct
type serviceOptions[A AggBase] struct {
	opts []ServiceOption[A]
}

// NewServiceOptions[A AggBase] new options struct
func NewServiceOptions[A AggBase]() *serviceOptions[A] {
	return new(serviceOptions[A])
}

func (_o *serviceOptions[A]) Options() []ServiceOption[A] {
	return _o.opts
}

func (_o *serviceOptions[A]) Append(_opts ...ServiceOption[A]) *serviceOptions[A] {
	_o.opts = append(_o.opts, _opts...)
	return _o
}

// Bus bus option of service
func (_o *serviceOptions[A]) Bus(bus Bus) *serviceOptions[A] {
	_o.opts = append(_o.opts, WithServiceBus[A](bus))
	return _o
}

// IdGenerator idGenerator option of service
func (_o *serviceOptions[A]) IdGenerator(idGenerator IDGenerator) *serviceOptions[A] {
	_o.opts = append(_o.opts, WithServiceIdGenerator[A](idGenerator))
	return _o
}

// WithServiceBus bus option of service
func WithServiceBus[A AggBase](bus Bus) ServiceOption[A] {
	return serviceOptionFunc[A](func(_s *service[A]) {
		_s.bus = bus
	})
}

// WithServiceIdGenerator idGenerator option of service
func WithServiceIdGenerator[A AggBase](idGenerator IDGenerator) ServiceOption[A] {
	return serviceOptionFunc[A](func(_s *service[A]) {
		_s.idGenerator = idGenerator
	})
}

func PrintServiceOptions(packageName string) {
	opts := []string{
		"WithServiceBus()",
		"WithServiceIdGenerator()",
	}
	if packageName == "" {
		fmt.Printf("opts := []ServiceOption{ \n")
		for _, v := range opts {
			fmt.Printf("	%s,\n", v)
		}
	} else {
		fmt.Printf("opts := []%s.ServiceOption{ \n", packageName)
		for _, v := range opts {
			fmt.Printf("	%s.%s,\n", packageName, v)
		}
	}
	fmt.Println("}")
}
