// Code generated by "gogen option -n Product -p _ -r AggBase"; DO NOT EDIT.

package product

import (
	"fmt"
	"github.com/ekuu/dgo"
	"github.com/ekuu/dgo/internal/examples/infra/types"
)

// New constructor
func New(aggBase dgo.AggBase, _opts ...Option) *Product {
	_p := new(Product)

	_p.AggBase = aggBase

	_p.SetOptions(_opts...)

	return _p
}

// Option option interface
type Option interface {
	apply(*Product)
}

// Option option function
type optionFunc func(*Product)

func (f optionFunc) apply(_p *Product) {
	f(_p)
}

func (_p *Product) SetOptions(_opts ...Option) *Product {
	for _, _opt := range _opts {
		_opt.apply(_p)
	}
	return _p
}

func SkipOption() Option {
	return optionFunc(func(_p *Product) {
		return
	})
}

func WithOptions(o *options) Option {
	return optionFunc(func(_p *Product) {
		_p.SetOptions(o.opts...)
	})
}

// options options struct
type options struct {
	opts []Option
}

// NewOptions new options struct
func NewOptions() *options {
	return new(options)
}

func (_o *options) Options() []Option {
	return _o.opts
}

func (_o *options) Append(_opts ...Option) *options {
	_o.opts = append(_o.opts, _opts...)
	return _o
}

// Name name option of Product
func (_o *options) Name(name string) *options {
	_o.opts = append(_o.opts, WithName(name))
	return _o
}

// Price price option of Product
func (_o *options) Price(price types.Fen) *options {
	_o.opts = append(_o.opts, WithPrice(price))
	return _o
}

// WithName name option of Product
func WithName(name string) Option {
	return optionFunc(func(_p *Product) {
		_p.name = name
	})
}

// WithPrice price option of Product
func WithPrice(price types.Fen) Option {
	return optionFunc(func(_p *Product) {
		_p.price = price
	})
}

func PrintOptions(packageName string) {
	opts := []string{
		"WithName()",
		"WithPrice()",
	}
	if packageName == "" {
		fmt.Printf("opts := []Option{ \n")
		for _, v := range opts {
			fmt.Printf("	%s,\n", v)
		}
	} else {
		fmt.Printf("opts := []%s.Option{ \n", packageName)
		for _, v := range opts {
			fmt.Printf("	%s.%s,\n", packageName, v)
		}
	}
	fmt.Println("}")
}
